speed up build times
Technove/AirplaneLite pull request #43
Opened 2021-07-14 22:43 UTC by Toffikk

2021-07-15 02:38 UTC, Titaniumtown commented
How does this speed up build times?

2021-07-15 04:47 UTC, PaulBGD commented
Maybe the incremental part? I'm not familiar with it though.

2021-07-15 05:46 UTC, jpenilla commented
Configuring UTF-8 encoding for Javadoc and ProcessResources is not a bad idea, however this PR does absolutely nothing whatsoever in terms of improving build times. In fact, this PR will probably slow down build times by forcing a fork and applying the java plugin to the root project where before it was only applied to subprojects.

2021-07-15 05:46 UTC, jpenilla requested changes

2021-07-15 05:46 UTC, jpenilla commented on build.gradle.kts
> +    tasks.withType<JavaCompile> { options.isFork = true; options.isIncremental = true; options.encoding = Charsets.UTF_8.name(); options.release.set(16) }
Have you heard of this thing called a newline?

2021-07-15 05:49 UTC, jpenilla commented
> Maybe the incremental part? I'm not familiar with it though.

It defaults to true. There is no need to set it manually.

2021-07-15 09:13 UTC, Toffikk commented
> Configuring UTF-8 encoding for Javadoc and ProcessResources is not a bad idea, however this PR does absolutely nothing whatsoever in terms of improving build times. In fact, this PR will probably slow down build times by forcing a fork and applying the java plugin to the root project where before it was only applied to subprojects.

The Java plugin was applied to the root project before too, and forcing a fork can speed up the build times in some cases

2021-07-15 09:52 UTC, jpenilla commented
I hadn't noticed it was applied to the root project, although it shouldn't be necessary to apply there, as the root project does not compile any java sources. It's possible paperweight is using it for something, I don't remember off the top of my head.

Regardless, it doesn't answer the question of why you are changing that block to apply to allprojects instead of subprojects. Those repositories and the java plugin don't need to be configured for the root project as it doesn't compile any java sources or pull anything from those repositories. I assume *maybe* it's because you want your changes to the java plugin to apply to the root project, but like I mentioned already it doesn't compile any java sources.

I also highly doubt that forcing a new process to be forked regardless of whether it's necessary will speed things up, feel free to provide a benchmark, or elaborate on what you mean by "in some cases" though.

2021-07-17 00:12 UTC, PaulBGD commented
Unconvinced this improves things, please benchmark it from a clean build.

2021-07-24 02:04 UTC, PaulBGD commented
Closing due to lack of a response.

2021-07-24 02:04 UTC, closed without merging